### PR TITLE
Upgrade to Tomcat 8

### PR DESCRIPTION
**Pull request by jkutner**

### CODE REVIEW

**Comment by jkutner** [comment]
Is this project still being actively maintained? Can I expect that a new version will be released once this change is merged?

I'm happy to help maintain it if you'd like. Or I fork it. Please let me know either way as this has been an important part of [webapp-runner](https://github.com/jsimone/webapp-runner). Thanks.

**Comment by zinin** [comment]
I think I should create new branch for Tomcat 8.
I'll try to merge your changes this weekend.

If I can't make changes this weekend, I can add you to repository Collaborators. What do you think about it?

**Comment by jkutner** [comment]
With webapp-runner I'm going to create a `7.x` branch, and make `master` the Tomcat 8 branch. But a dedicated Tomcat 8 branch on tomcat-redis-session seems fine too, as long as we can still release a new version of it.  

Maybe there should be a new line of versioning for Tomcat 8? For webapp-runner, [we will keep the major version pinned to the Tomcat version](http://search.maven.org/#browse|-2139724589). 

I would love to be added to the project as a Collaborator. But I will still want to respect your decisions with regard to branching and versioning. 

Thanks for your help!

**Comment by zinin** [comment]
Did you test this code on real projects on Tomcat 8 with redis session manager?
I think that I need some time to migrate my projects to Tomcat 8 and see how it works.

**Comment by jkutner** [comment]
Yes, I have tested with this simple project:
https://github.com/kissaten/webapp-runner-redis

**Comment by jkutner** [comment]
Do you have a feeling for how long it will be before you are able to test, merge and release this? I'm anxious to update webapp-runner, and given the volume of change here, I may just fork and package this into my project (but I'd rather not).

**Comment by zinin** [comment]
I thought that I should create another project instead of branch, i.e. tomcat8-redis-session.
And release it to maven central.
Now I have a lot of work and I think I can do it within 1-4 weeks.

**Comment by zinin** [comment]
So if you're in a hurry you'd better to fork.

**Pull request closed without merging**
